# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Rotas's Blog
subtitle: '今日无事可做'
description: ''
keywords:
  - '编程'
  - '数学'
  - 'C++'
author: Rotas
language: zh-CN
timezone: 'Asia/Shanghai'
navbar:
  blog_title: Rotas's Blog
  menu:
    - { key: 'home', link: '/', icon: 'iconfont icon-home-fill' }
    - { key: 'archives', link: '/archives/', icon: 'iconfont icon-note', name: '归档' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill', name: '标签' }
    - { key: 'categories', link: '/categories/', icon: 'iconfont icon-books', name: '分类' }
index:
  slogan:
    enable: true
    text: 今日无事可做
  post_sticky:
    enable: true
    icon: 'iconfont icon-top'
  post_url_target: _blank
  banner_img: /assets/website/banner3.jpg

archive:
  banner_img: /assets/website/banner1.jpg
tag:
  banner_img: /assets/website/banner1.jpg
category:
  banner_img: /assets/website/banner1.jpg

custom_css:
  - /css/custom.css
font:  # 主题字体配置
  font_size: 16px        # 全局字号
  font_family:
  code_font_size: 85%    # 代码的字号

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://rotaxs.github.io/
# permalink: :year/:month/:day/:title/
permalink: :category/:post_title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
# i18n_dir: :lang
i18n_dir:
  - zh-CN
  - en
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
# syntax_highlighter: highlight.js
# highlight:
#   line_number: true
#   auto_detect: false
#   tab_replace: ''
#   wrap: true
#   hljs: false
# prismjs:
#   preprocess: true
#   line_number: true_self
#   tab_replace: ''

post:
  math:
    enable: true
    specific: true
    engine: katex
  mermaid:
    enable: true
    specific: true
    options:
  meta:
    author:  # 作者，优先根据 front-matter 里 author 字段，其次是 hexo 配置中 author 值
      enable: false
    date:  # 文章日期，优先根据 front-matter 里 date 字段，其次是 md 文件日期
      enable: true
      format: "YYYY 年 MM 月 DD 日, dddd"  # 格式参照 ISO-8601 日期格式化
      # format: "dddd, MMMM Do YYYY, h:mm"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{} 字"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: true
      format: "{} 分钟"
    views:  # 阅读次数
      enable: false
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi | openkounter   注意不蒜子会间歇抽风
      format: "{} 次"
  banner_img: /assets/website/banner1.jpg
  footnote:
    enable: true
    header: ''

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "prismjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 未分类
category_map:
  "博客": blogs
  "计算机": computer
  "数学": math
tag_map:
  "博客": blogs
  "计算机": computer
  "数学": math
  "教程": tutorials
  "笔记": notes
  "配置": configures

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:Rotaxs/Rotaxs.github.io.git
    branch: gh-pages

markdown:
  preset: "default"
  render:
    html: true
    xhtmlOut: false
    langPrefix: "language-"
    breaks: true
    linkify: true
    typographer: true
    quotes: "“”‘’"
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-deflist
    # - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-checkbox
    - markdown-it-imsize
    - markdown-it-expandable
    - '@renbaoshuo/markdown-it-katex'
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: tips
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: false
    permalinkClass: "header-anchor"
    permalinkSide: "left"
    permalinkSymbol: "¶"
    case: 0
    separator: "-"